package cern.colt.matrix

import cern.colt.matrix.impl._

object MatrixTypes {
  type DoubleMatrix1D = Matrix1D[Double]
  type DenseColumnDoubleMatrix2D = DenseColumnMatrix2D[Double]
  type DenseDoubleMatrix1D = DenseMatrix1D[Double]
  type DenseDoubleMatrix2D = DenseMatrix2D[Double]
  type DenseLargeDoubleMatrix2D = DenseLargeMatrix2D[Double]
  type DiagonalDoubleMatrix2D = DiagonalMatrix2D[Double]
  type WrapperDoubleMatrix1D = WrapperMatrix1D[Double]
  type WrapperDoubleMatrix2D = WrapperMatrix2D[Double]
  type SparseCCDoubleMatrix2D = SparseCCMatrix2D[Double]
  type SparseCCMDoubleMatrix2D = SparseCCMMatrix2D[Double]
  type SparseDoubleMatrix1D = SparseMatrix1D[Double]
  type SparseDoubleMatrix2D = SparseHashMatrix2D[Double]
  type SparseRCDoubleMatrix2D = SparseRCMatrix2D[Double]
  type SparseRCMDoubleMatrix2D = SparseRCMMatrix2D[Double]

  type DenseColumnFloatMatrix2D = DenseColumnMatrix2D[Float]
  type DenseFloatMatrix1D = DenseMatrix1D[Float]
  type DenseFloatMatrix2D = DenseMatrix2D[Float]
  type DenseLargeFloatMatrix2D = DenseLargeMatrix2D[Float]
  type DiagonalFloatMatrix2D = DiagonalMatrix2D[Float]
  type WrapperFloatMatrix1D = WrapperMatrix1D[Float]
  type WrapperFloatMatrix2D = WrapperMatrix2D[Float]
  //type SparseCCFloatMatrix2D = SparseCCMatrix2D[Float]
  type SparseCCMFloatMatrix2D = SparseCCMMatrix2D[Float]
  type SparseFloatMatrix1D = SparseMatrix1D[Float]
  type SparseFloatMatrix2D = SparseHashMatrix2D[Float]
  //type SparseRCFloatMatrix2D = SparseRCMatrix2D[Float]
  type SparseRCMFloatMatrix2D = SparseRCMMatrix2D[Float]

  type DenseColumnIntMatrix2D = DenseColumnMatrix2D[Int]
  type DenseIntMatrix1D = DenseMatrix1D[Int]
  type DenseIntMatrix2D = DenseMatrix2D[Int]
  type DenseLargeIntMatrix2D = DenseLargeMatrix2D[Int]
  type DiagonalIntMatrix2D = DiagonalMatrix2D[Int]
  type WrapperIntMatrix1D = WrapperMatrix1D[Int]
  type WrapperIntMatrix2D = WrapperMatrix2D[Int]
  //type SparseCCIntMatrix2D = SparseCCMatrix2D[Int]
  type SparseCCMIntMatrix2D = SparseCCMMatrix2D[Int]
  type SparseIntMatrix1D = SparseMatrix1D[Int]
  type SparseIntMatrix2D = SparseHashMatrix2D[Int]
  //type SparseRCIntMatrix2D = SparseRCMatrix2D[Int]
  type SparseRCMIntMatrix2D = SparseRCMMatrix2D[Int]

  type DenseColumnLongMatrix2D = DenseColumnMatrix2D[Long]
  type DenseLargeLongMatrix2D = DenseLargeMatrix2D[Long]
  type DenseLongMatrix1D = DenseMatrix1D[Long]
  type DenseLongMatrix2D = DenseMatrix2D[Long]
  type DiagonalLongMatrix2D = DiagonalMatrix2D[Long]
  type WrapperLongMatrix1D = WrapperMatrix1D[Long]
  type WrapperLongMatrix2D = WrapperMatrix2D[Long]
  type DenseColumnObjectMatrix2D = DenseColumnMatrix2D[Object]
  type DenseLargeObjectMatrix2D = DenseLargeMatrix2D[Object]
  //type SparseCCLongMatrix2D = SparseCCMatrix2D[Long]
  type SparseCCMLongMatrix2D = SparseCCMMatrix2D[Long]
  type SparseLongMatrix1D = SparseMatrix1D[Long]
  type SparseLongMatrix2D = SparseHashMatrix2D[Long]
  //type SparseRCLongMatrix2D = SparseRCMatrix2D[Long]
  type SparseRCMLongMatrix2D = SparseRCMMatrix2D[Long]

  type DenseObjectMatrix1D = DenseMatrix1D[Object]
  type DenseObjectMatrix2D = DenseMatrix2D[Object]
  type DiagonalObjectMatrix2D = DiagonalMatrix2D[Object]
  type WrapperObjectMatrix1D = WrapperMatrix1D[Object]
  type WrapperObjectMatrix2D = WrapperMatrix2D[Object]
  //type SparseCCObjectMatrix2D = SparseCCMatrix2D[Object]
  type SparseCCMObjectMatrix2D = SparseCCMMatrix2D[Object]
  type SparseObjectMatrix1D = SparseMatrix1D[Object]
  type SparseObjectMatrix2D = SparseHashMatrix2D[Object]
  //type SparseRCObjectMatrix2D = SparseRCMatrix2D[Object]
  type SparseRCMObjectMatrix2D = SparseRCMMatrix2D[Object]
}
